options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: "python:3.9"
    id: "Install dependencies"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Installing dependencies..."
        pip install --upgrade pip
        pip install -r requirements.txt
        if [ $? -ne 0 ]; then
          echo "Dependency installation failed"
          exit 1
        fi

  - name: "python:3.9"
    id: "Create GCP Compute Disk"
    entrypoint: "python"
    args:
      - "create-disk.py"

timeout: "600s"
