steps:
  # Step 1: Install dependencies
  - name: "python:3.9"
    id: "Install dependencies"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install -r requirements.txt

  # Step 2: Execute the Python script
  - name: "python:3.9"
    id: "Create GCP Compute Disk"
    entrypoint: "python"
    args:
      - "create_disk.py"

timeout: "600s"
